// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "cross-crossaccte",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "cross",
            "endpoint": "https://qao7qn1l82.execute-api.us-east-1.amazonaws.com/crossaccte",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "crossaccounttest-20190816111747-hostingbucket-crossaccte",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://crossaccounttest-20190816111747-hostingbucket-crossaccte.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
